// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestEngine.Data;

namespace QuestEngine.Data.Migrations
{
    [DbContext(typeof(QuestEngineContext))]
    partial class QuestEngineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuestEngine.Data.Models.PlayerProgress", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(50);

                    b.Property<int>("QuestId");

                    b.Property<int?>("LastMilestoneCompletedId");

                    b.Property<long>("QuestPointsEarned");

                    b.HasKey("PlayerId", "QuestId");

                    b.ToTable("PlayerProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
